import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage()
await page.setViewportSize({ width: 1280, height: 900 })
await page.goto('http://localhost:5173/')
await page.waitForSelector('text=Returns Processed', { timeout: 6000 })
await page.waitForTimeout(400)
await page.screenshot({ path: '/tmp/home_final.png', fullPage: true })
console.log('done')
await browser.close()
